config/routes.rb
FeedMeRails::Application.routes.draw do
  resources :orders

  get "pages/home"

  devise_for :restaurants

  resources :ratings do
    collection do
      post 'search'
    end
  end

  resources :dishes

  resources :menus

  resources :customers do
    collection do
      post 'waiter'
    end
  end

  resources :restaurants

  resources :users

  match 'waiter.json', :controller => 'customers', :action => 'waiter', :format => 'json' 

  root to: "pages#home" 

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :restaurant_id
  
  belongs_to :restaurant
  has_many :dishes
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])
    @dishes = @menu.dishes
    @dish = Dish.new
    @images = []
    
    @menu.dishes.each do |dish|
	        @images << dish.image
	  end
	
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h1>Listing menus</h1>

<table>
  <tr>
    <th>Restaurant</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menus.each do |menu| %>
  <tr>
    <td><%= menu.restaurant_id %></td>
    <td><%= link_to 'Show', menu %></td>
    <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
    <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<div id="menu">

<div id="menu_buttons">
  <div class="row">
    <div class="span10">
	<center><h1 id="menu_title"><%= current_restaurant.name %>'s menu</h1></center>
	

      <li style="list-style:none;margin-bottom:3em" class="dropdown" id="menu1">
    <a class="btn btn-large btn-primary" data-toggle="dropdown" href="#menu1">Add a dish</a>

    <ul class="dropdown-menu">
      <li><%= render partial: "dishes/form" %></li>
    </ul>
  </li>

<% if @dishes.count >= 1 %>
  <% @dishes.each do |dish| %>
  <div class="row">
	<div class="span10" id="menu_info">
    	<div><center><p class="menu_content" id="name_of_dish"><%= dish.name %></p></center></div>   
    </div>
  </div>
  <div class="row">
	<div class="span3">
	    <p><a href="#"><img src="<%= dish.image %>" class="food_image_for_menu" %></a></p>
	</div>
	<div class="span4">
		<p class="menu_content"><%= number_to_currency(dish.price) %></p>
	    <p class="menu_content"><%= dish.description %></p>
	</div>
	<div class="span2">
	    <p class="menu_content"><%= dish.ratings unless dish.ratings.empty? %></p>
	</div>
	<div class="span1">
	    <%= link_to("Edit", edit_dish_path(dish), :class => "btn btn-large btn-primary", :id => "edit_dish_button") %>
	</div>
  </div>

  <% end %>

<% end %>


</div>