config/routes.rb
FeedMeRails::Application.routes.draw do
  resources :orders

  get "pages/home"

  devise_for :restaurants

  resources :ratings do
    collection do
      post 'search'
    end
  end

  resources :dishes

  resources :menus

  resources :customers do
    collection do
      post 'waiter'
    end
  end

  resources :restaurants

  resources :users

  match 'waiter.json', :controller => 'customers', :action => 'waiter', :format => 'json' 

  root to: "pages#home" 

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :dish_id, :user_id, :value, :comment
  
  belongs_to :user
  belongs_to :dish
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
    @rating = Rating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.json
  def new
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(params[:rating])
    facebook_id = params[:rating][:user_id]
    @user = User.find_by_facebook_id(facebook_id)
    @rating.user_id = @user.id
    dish = Dish.find(params[:rating][:dish_id])    
    @rating.dish_id = dish.id   
  
    respond_to do |format|
      if @rating.save
        if @rating.value == 1
          dish.upvotes += 1
        else
          dish.downvotes += 1
        end
        dish.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render json: @rating, status: :created, location: @rating }
      else
        format.html { render action: "new" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.json
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url }
      format.json { head :no_content }
    end
  end

  def search
    restaurant = Restaurant.find(params[:restaurant_id])
    menu = restaurant.menu
    @ratings = []
    menu.dishes.each do |dish|
      dish.ratings.each do |rating|
        @ratings.push(rating)
      end
    end

    respond_to do |format|
      format.json { render json: @ratings }
    end
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :dish_id %><br />
    <%= f.number_field :dish_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <tr>
    <th>User</th>
    <th>Dish</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ratings.each do |rating| %>
  <tr>
    <td><%= rating.user_id %></td>
    <td><%= rating.dish_id %></td>
    <td><%= link_to 'Show', rating %></td>
    <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
    <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @rating.user_id %>
</p>

<p>
  <b>Dish:</b>
  <%= @rating.dish_id %>
</p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>