config/routes.rb
FeedMeRails::Application.routes.draw do
  resources :orders

  get "pages/home"

  devise_for :restaurants

  resources :ratings do
    collection do
      post 'search'
    end
  end

  resources :dishes

  resources :menus

  resources :customers do
    collection do
      post 'waiter'
    end
  end

  resources :restaurants

  resources :users

  match 'waiter.json', :controller => 'customers', :action => 'waiter', :format => 'json' 

  root to: "pages#home" 

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container"><!-- Collapsable nav bar -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Site name -->
      <% if current_restaurant %><%= link_to "Feed.me", menu_path(current_restaurant.menu.id), :class => "brand" %>
      <% else %> <%= link_to "Feed.me", root_path, :class => "brand" %>
      <% end %>
 
      <!-- Start of the nav bar content -->
      <div class="nav-collapse"><!-- Other nav bar content -->
       
        <!-- The drop down menu -->
        <ul class="nav pull-right">
          <li class="divider-vertical"></li>
          <% if !restaurant_signed_in? %>
          <li class="drop down">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">
	          Sign In <strong class="caret"></strong></a>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
              	<%= render :partial => "devise/sessions/new" %>
            </div>
          </li>
          <% else %>
          <li class="drop down">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">
	          User <strong class="caret"></strong></a>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
              	
<%= link_to "Edit profile", edit_restaurant_path(current_restaurant), :class => "btn btn-large btn-primary", :id => "sign_out_button" %>
<%= link_to "Sign out", destroy_restaurant_session_path, :method => :delete, :class => "btn btn-large btn-primary", :id => "sign_out_button" %>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeedMeRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div id="content">
    <%= yield %>
  </div>
<%= render "layouts/footer" %>
</body>
</html>